spring:
  application:
    name: discord-clone-server

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: rkddn123
    key-store-type: PKCS12
    key-alias: bootsecurity